### ISSUE TITLE
django-allauth 0.55 compatibility

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#138]
django-allauth `0.55` (released August 22) has [multiple backwards incompatible issues in their changelog](https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst#0550-2023-08-22), and at least <s>one</s> two of them makes it incompatible with Trix 3.0.0:

> A large internal refactor has been performed to be able to add support for providers oferring one or more subproviders. This refactor has the following impact:
> -  The provider registry methods `get_list()`, `by_id()` have been removed. The registry now only providers access to the provider classes, not the instances.
> - `provider.get_app()` has been removed -- use provider.app instead.
> - (...)

This doesn't work with Trix 3.0.0: `AttributeError: 'ProviderRegistry' object has no attribute 'get_list'`.

**Comment by Levijatan** [comment]
Hopefully fixed inn e6699e3
